---
title: "Lab 02 - Plastic waste"
author: "Insert your name here"
date: "Insert date here"
output: github_document
---

## Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
plastic_waste <- read.csv("data/plastic-waste.csv")
```

## Exercises

### Exercise 1

Remove this text, and add your answer for Exercise 1 here.

```{r plastic-waste-continent}
# insert code here
```

### Exercise 2

```{r plastic-waste-density}
# insert code here
```

### Exercise 3

Remove this text, and add your answer for Exercise 3 here.

```{r plastic-waste-violin}
# insert code here
```

### Exercise 4

Remove this text, and add your answer for Exercise 4 here.

```{r plastic-waste-mismanaged}
# insert code here
```

```{r plastic-waste-mismanaged-continent}
# insert code here
```

```{r plastic-waste-population-total}
# insert code here
```

```{r plastic-waste-population-coastal}
# insert code here
```

### Exercise 5

Remove this text, and add your answer for Exercise 5 here.

```{r recreate-viz}
# insert code here
```


